name: Run Tests

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install --upgrade pip; pip install -r requirements.txt;

      - name: Run tests
        run: pytest --cache-clear --cov > pytest-coverage.txt

      - name: Get Cover 
        uses: orgoro/coverage@v3.1
        with:
          coverageFile: pytest-coverage.txt
